FROM cgr.dev/chainguard-private/python:3.10-dev

WORKDIR /app

COPY pyproject.toml .
RUN --mount=type=secret,id=uv_toml,dst=/app/uv.toml,mode=0444 uv sync

COPY secret.cfg .

COPY static ./static

COPY app.py .

ENTRYPOINT ["/usr/bin/uv", "run", "--no-sync", "app.py"]
